#!/bin/sh

overlay_is_active()
{
    if [ -e /overlay/robase/overlay ] ; then
        return 0
    else
        return 1
    fi
}

if [ $# -eq 0 ] ; then
    echo "overlayctl [status|enable|disable|lock|unlock]"
    exit 0
fi

if overlay_is_active ; then
    overlay_active="yes"
    overlay_base="/overlay/robase/"
else
    overlay_active="no"
    overlay_base="/"
fi

overlay_disable_file="$overlay_base""overlay/disable"

case "$1" in
    status)
        echo -n "overlay is "
        if [ "$overlay_active" = "yes" ] ; then
            echo "active"
        else
            echo "inactive"
        fi
        echo -n "overlay "
        if [ -e "$overlay_disable_file" ] ; then
            echo -n "disabled"
        else
            echo -n "enabled"
        fi
        echo " for next boot"
        ;;

    enable)
        if [ -e "$overlay_disable_file" ] ; then
            if [ -w "$overlay_base/overlay" ] ; then
               rm "$overlay_disable_file"
            else
               mount -o remount,rw "$overlay_base"
               rm "$overlay_disable_file"
               mount -o remount,ro "$overlay_base"
            fi
        fi
        ;;

    disable)
        if [ ! -e "$overlay_disable_file" ] ; then
            if [ -w "$overlay_base/overlay" ] ; then
               echo 1 >"$overlay_disable_file"
            else
               mount -o remount,rw "$overlay_base"
               echo 1 >"$overlay_disable_file"
               mount -o remount,ro "$overlay_base"
            fi
        fi
        ;;

    lock)
        mount -o remount,ro "$overlay_base"
        ;;

    unlock)
        mount -o remount,rw "$overlay_base"
        ;;

    *)
        echo "overlayctl: unknown option"
        exit 1
        ;;
esac
